name: 'GCP Authentication'
description: 'Deploy to Google Cloud Platform'
inputs:
  project_id:
    description: 'GCP Project ID'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel
          CHECK_VERSION=$(ls dist/*-${GITHUB_REF#refs/tags/}*.tar.gz)

      - name: Connecting Artifact Registry for twine
        run: |
          pip install keyring
          pip install keyrings.google-artifactregistry-auth

      - name: Upload package to Google Artifact Registry
        env:
          TWINE_REPOSITORY_URL: https://europe-west1-python.pkg.dev/${{ vars.project_id }}/pypi-custom
        run: twine upload --non-interactive dist/*
