name: 'Publish to Google Artifact Registry'
description: 'Deploy Pypi package to Google Artifact Registry'
inputs:
  project_id:
    description: 'GCP Project ID'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Python package
        shell: bash
        run: |
          python setup.py sdist bdist_wheel
          CHECK_VERSION=$(ls dist/*-${GITHUB_REF#refs/tags/}*.tar.gz)

      - name: Connecting Artifact Registry for twine
        shell: bash
        run: |
          pip install keyring
          pip install keyrings.google-artifactregistry-auth

      - name: Upload package to Google Artifact Registry
        shell: bash
        env:
          TWINE_REPOSITORY_URL: https://europe-west1-python.pkg.dev/${{ inputs.project_id }}/pypi-custom
        run: twine upload --non-interactive dist/*
